routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Auth::routes();

Route::get('/home', 'ProductsController@index')->name('home');

Route::resource('products','ProductsController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['art', 'name'];
	
	public function getCreatedDateAttribute()
	{
		return $this->created_at->format('Y-m-d');
	}
}

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Role extends Model
{
    protected $fillable = ['slug', 'name'];
	
	public function users()
    {
        return $this->hasMany('App\User', 'role_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Permissions\HasPermissionsTrait;
use App\Role;

class User extends Authenticatable
{
    use Notifiable, HasPermissionsTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'page_id', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
		$users = User::all();
		
        return view('home.index', compact('users') );
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Http\Requests\ProductFormRequest;

class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::latest()->paginate(5);
		
		return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
		$product = new Product();
		
        return view('products.create', compact('product'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\ProductFormRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductFormRequest $request)
    {
		Product::create($request->all());
		
		return redirect()->route('products.index')->with('success', 'Продукт успешно создан');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\ProductFormRequest  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(ProductFormRequest $request, Product $product)
    {
		$product->update($request->all());
		
		return redirect()->route('products.index')->with('success', 'Продукт успешно отредактирован');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
		$product->delete(); 
		
		return redirect()->route('products.index')->with('success', 'Продукт успешно удален');
    }
}

app/Http/Controllers/RolesController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use Illuminate\Http\Request;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        //
    }
}

resources/views/home/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
			<div class="row table">
				<div class="col-md-1">№</div>
				<div class="col-md-2">Имя</div>
				<div class="col-md-3">Email</div>
				<div class="col-md-5">Пароль</div>
			</div>
			@foreach($users as $user)
				<div class="row table">
					<div class="col-md-1">{!! $user->id !!}</div>
					<div class="col-md-2">{!! $user->name !!}</div>
					<div class="col-md-3">{!! $user->email !!}</div>
					<div class="col-md-5">123456</div>
				</div>
			@endforeach
        </div>
    </div>
	<div class="row justify-content-center">
        <div class="col-md-12">
			<p>Сomposer-пакет для Laravel 5, содержащий и реализующий нижеследующее Функционал: добавление и редактирование продуктов.</p>
		</div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="pull-left">
						<h2>Добавление продукта</h2>
					</div>
					<div class="pull-right">
						<a href="{{ route('products.index') }}">Список продуктов</a>
					</div>					
				</div>
				<div class="card-body">
					<form method="post" action="{{ route('products.store') }}">
						@csrf
						@include ('products.form', ['button' => 'Создать продукт']) 
					</form>
				</div>
			</div>
		</div>
    </div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
			<div class="card">
				<div class="card-header">
					<div class="pull-left">
						<h2>Редактирование продукта</h2>
					</div>					
					<div class="pull-right">
						<a href="{{ route('products.index') }}">Список продуктов</a>
					</div>	
				</div>
				<div class="card-body">
					<form method="post" action="{{ route('products.update', $product->id) }}">
						@csrf
						@method('PUT')
						@include ('products.form', ['method' => 'put', 'button' => 'Обновить продукт']) 
				  </form>
				</div>
			</div>
		</div>
    </div>
</div>
@endsection

resources/views/products/form.blade.php
@role('admin')								
	<div class="form-group">
		<label for="name">Артикул:</label>
		<input type="text" value="{{ old('art', $product->art) }}" class="form-control {{ $errors->has('art') ? 'is-invalid' : '' }}" name="art" />
		@if ($errors->has('art'))
			<span class="text-danger">{{ $errors->first('art') }}</span>
		@endif
	</div>
@endrole
<div class="form-group">
	<label for="price">Название:</label>
	<input type="text" value="{{ old('name', $product->name) }}" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" name="name" />
	@role('manager')								
		<input type="hidden" value="{{ old('art', $product->art) }}" name="art" />
	@endrole

	@if ($errors->has('name'))
		<span class="text-danger">{{ $errors->first('name') }}</span>
	@endif
</div>
<button type="submit" class="btn btn-primary">{{ $button }}</button>

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
			@if(session()->get('success'))
				<div class="alert alert-success">
					{{ session()->get('success') }}  
				</div>
			@endif
            <div class="card">
				<div class="card-header">
					<div class="row">
						<div class="col-md-10">
							<h1>Список товаров</h1>
						</div>
						<div class="col-md-2">
							@role('admin', 'manager')								
								<a href="{{ route('products.create') }}" class="btn btn-success">Создать товар</a>
							@endrole
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach ($products as $product)
						<div class="media">
							<div class="media-body">
								<h3 class="mt-0">{{ $product->name }}</h3>
								{{ $product->art }}
								<small class="text-muted">{{ $product->created_date}}</small>
								<br/>
								@role('admin', 'manager')								
									<form action="{{ route('products.destroy', $product->id) }}" method="post">
										<a href="{{ route('products.edit', $product->id) }}" class="btn btn-primary">Обновить</a>
										@csrf
										@method('DELETE')
										<button class="btn btn-danger" type="submit">Удалить</button>
									</form>
								@endrole
							</div>
						</div>
						<hr>
					@endforeach
					
					{{ $products->links() }}
				</div>
            </div>
        </div>
    </div>
</div>
@endsection